project:
  name: quickstart-citrix-adc-waf
  owner: quickstart-eng@amazon.com
  package_lambda: false
  s3_regional_buckets: true
  shorten_stack_name: true
  regions:
  - us-east-1
  - us-east-2
  - us-west-1
  - us-west-2
  - ca-central-1
  - eu-central-1
  - eu-west-1
  - eu-west-2
  - ap-southeast-1
  - ap-southeast-2
  - ap-south-1
  - ap-northeast-1
  - ap-northeast-2
  - sa-east-1
  s3_bucket: ''
  parameters:
    KeyPairName: $[taskcat_getkeypair]
    QSS3BucketName: $[taskcat_autobucket]
    QSS3BucketRegion: $[taskcat_current_region]
    RestrictedSSHCIDR: 10.0.0.0/16
    RestrictedWebAppCIDR: 10.0.0.0/16

tests:
  citrix-waf-master-ap-northeast-1:
    parameters:
      PrimaryAvailabilityZone: ap-northeast-1b
      SecondaryAvailabilityZone: ap-northeast-1c
    regions:
    - ap-northeast-1
    s3_bucket: ''
    template: ./templates/citrix-adc-waf-master.template.yaml
  citrix-waf-master-ap-northeast-2:
    parameters:
      PrimaryAvailabilityZone: ap-northeast-2a
      SecondaryAvailabilityZone: ap-northeast-2c
    regions:
    - ap-northeast-2
    s3_bucket: ''
    template: ./templates/citrix-adc-waf-master.template.yaml
  citrix-waf-master-ap-south-1:
    parameters:
      PrimaryAvailabilityZone: ap-south-1a
      SecondaryAvailabilityZone: ap-south-1b
    regions:
      - ap-south-1
    s3_bucket: ''
    template: ./templates/citrix-adc-waf-master.template.yaml
  citrix-waf-master-ap-southeast-1:
    parameters:
      PrimaryAvailabilityZone: ap-southeast-1a
      SecondaryAvailabilityZone: ap-southeast-1b
    regions:
      - ap-southeast-1
    s3_bucket: ''
    template: ./templates/citrix-adc-waf-master.template.yaml
  citrix-waf-master-ap-southeast-2:
    parameters:
      PrimaryAvailabilityZone: ap-southeast-2a
      SecondaryAvailabilityZone: ap-southeast-2b
    regions:
      - ap-southeast-2
    s3_bucket: ''
    template: ./templates/citrix-adc-waf-master.template.yaml
  citrix-waf-master-ca-central-1:
    parameters:
      PrimaryAvailabilityZone: ca-central-1a
      SecondaryAvailabilityZone: ca-central-1b
    regions:
      - ca-central-1
    s3_bucket: ''
    template: ./templates/citrix-adc-waf-master.template.yaml
  citrix-waf-master-eu-central-1:
    parameters:
      PrimaryAvailabilityZone: eu-central-1a
      SecondaryAvailabilityZone: eu-central-1b
    regions:
      - eu-central-1
    s3_bucket: ''
    template: ./templates/citrix-adc-waf-master.template.yaml
  citrix-waf-master-eu-west-1:
    parameters:
      PrimaryAvailabilityZone: eu-west-1a
      SecondaryAvailabilityZone: eu-west-1b
    regions:
      - eu-west-1
    s3_bucket: ''
    template: ./templates/citrix-adc-waf-master.template.yaml
  citrix-waf-master-eu-west-2:
    parameters:
      PrimaryAvailabilityZone: eu-west-2a
      SecondaryAvailabilityZone: eu-west-2b
    regions:
      - eu-west-2
    s3_bucket: ''
    template: ./templates/citrix-adc-waf-master.template.yaml
  citrix-waf-master-sa-east-1:
    parameters:
      PrimaryAvailabilityZone: sa-east-1b
      SecondaryAvailabilityZone: sa-east-1c
    regions:
      - sa-east-1
    s3_bucket: ''
    template: ./templates/citrix-adc-waf-master.template.yaml
  citrix-waf-master-us-east-1:
    parameters:
      PrimaryAvailabilityZone: us-east-1a
      SecondaryAvailabilityZone: us-east-1b
    regions:
      - us-east-1
    s3_bucket: ''
    template: ./templates/citrix-adc-waf-master.template.yaml
  citrix-waf-master-us-east-2:
    parameters:
      PrimaryAvailabilityZone: us-east-2a
      SecondaryAvailabilityZone: us-east-2b
    regions:
      - us-east-2
    s3_bucket: ''
    template: ./templates/citrix-adc-waf-master.template.yaml
  citrix-waf-master-us-west-1:
    parameters:
      PrimaryAvailabilityZone: us-west-1a
      SecondaryAvailabilityZone: us-west-1c
    regions:
      - us-west-1
    s3_bucket: ''
    template: ./templates/citrix-adc-waf-master.template.yaml
  citrix-waf-master-us-west-2:
    parameters:
      PrimaryAvailabilityZone: us-west-2a
      SecondaryAvailabilityZone: us-west-2b
    regions:
      - us-west-2
    s3_bucket: ''
    template: ./templates/citrix-adc-waf-master.template.yaml
