project:
  name: quickstart-citrix-adc-waf
  owner: quickstart-eng@amazon.com
  package_lambda: false
  s3_regional_buckets: true
  shorten_stack_name: true
  regions:
  - us-east-1
  - us-east-2
  - us-west-1
  - us-west-2
  - ca-central-1
  - eu-central-1
  - eu-west-1
  - eu-west-2
  - ap-southeast-1
  - ap-southeast-2
  - ap-south-1
  - ap-northeast-1
  - ap-northeast-2
  - sa-east-1
  s3_bucket: ''
tests:
  citrix-waf-master-us-west-1:
    parameters:
      KeyPairName: $[taskcat_getkeypair]
      QSS3BucketName: $[taskcat_autobucket]
      QSS3BucketRegion: $[taskcat_current_region]
      PrimaryAvailabilityZone: us-west-1a
      SecondaryAvailabilityZone: us-west-1c
      RestrictedSSHCIDR: 204.246.162.44/32
      RestrictedWebAppCIDR: 204.246.162.44/32
    regions:
    - us-west-1
    s3_bucket: ''
    template: templates/citrix-adc-waf-master.template.yaml
